services:
  - type: web
    name: whatsapp-crm-backend
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: API_SECRET_KEY
        sync: false
      - key: WA_VERIFY_TOKEN
        sync: false
      - key: WA_ACCESS_TOKEN
        sync: false
      - key: WA_PHONE_NUMBER_ID
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: CRM_PROVIDER
        value: internal
